#!/usr/bin/env python3
# Author: Tim Rice <tim.j.rice@hackrange.com>
# Part of nextgen-dast. See README.md for license and overall architecture.
"""
Information disclosure: backup / config files exposed at the public
web root.

A `/.env` reachable on the production origin hands the attacker
every secret the app has -- DB credentials, API keys, signing
secrets. `/dump.sql` is a full database export. `/.git/config` is
the seed for cloning the entire source tree from the live web
server. `/id_rsa` is, well, the private key.

Different from `info_directory_listing` (which detects autoindex)
and `info_key_material_exposed` (which targets `/encryptionkeys`
and friends). This probe walks a focused catalogue of named files
that should NEVER be public, and -- crucially -- pattern-matches
the response body against a per-file signature so an SPA returning
its `index.html` for any unknown path doesn't false-positive.

Detection signal:
  GET each path. Validate when the status is 200 AND the body
  matches the file's signature regex (e.g. `/.env` body must
  contain `^[A-Z_][A-Z0-9_]*=` lines).

Tested against:
  + OWASP Juice Shop  /.env etc. fall through to the SPA's
                      index.html which doesn't match the per-file
                      signatures -> validated=False.
  + Apps with stray backup or repo files at the root
    -> validated=True.

Read-only: GET only.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import urljoin, urlparse

sys.path.insert(0, str(Path(__file__).parent.parent))
from lib import Probe, Verdict, SafeClient   # noqa: E402

# Each entry is (path, signature_regex, label). The regex is
# anchored to require a structural element of the file format -- so
# an SPA returning `<!doctype html>` to every path doesn't fire on
# any of them.
TARGETS: tuple[tuple[str, re.Pattern, str], ...] = (
    ("/.env",
     re.compile(r"(?m)^[A-Z][A-Z0-9_]*\s*=\s*.+$"),
     ".env (KEY=VALUE)"),
    ("/.env.local",
     re.compile(r"(?m)^[A-Z][A-Z0-9_]*\s*=\s*.+$"),
     ".env.local"),
    ("/.env.production",
     re.compile(r"(?m)^[A-Z][A-Z0-9_]*\s*=\s*.+$"),
     ".env.production"),
    ("/.env.development",
     re.compile(r"(?m)^[A-Z][A-Z0-9_]*\s*=\s*.+$"),
     ".env.development"),
    ("/config.json",
     re.compile(r'^\s*\{[^"]*"[A-Za-z_]+"\s*:'),
     "config.json"),
    ("/config.yaml",
     re.compile(r"(?m)^[A-Za-z_][A-Za-z0-9_]*\s*:\s*"),
     "config.yaml"),
    ("/config.yml",
     re.compile(r"(?m)^[A-Za-z_][A-Za-z0-9_]*\s*:\s*"),
     "config.yml"),
    ("/database.sql",
     re.compile(r"INSERT\s+INTO|CREATE\s+TABLE", re.I),
     "database.sql"),
    ("/dump.sql",
     re.compile(r"INSERT\s+INTO|CREATE\s+TABLE", re.I),
     "dump.sql"),
    ("/backup.sql",
     re.compile(r"INSERT\s+INTO|CREATE\s+TABLE", re.I),
     "backup.sql"),
    ("/.git/config",
     re.compile(r"\[core\]\s+repositoryformatversion"),
     "git config"),
    ("/.git/HEAD",
     re.compile(r"^\s*ref:\s+refs/heads/"),
     ".git/HEAD"),
    ("/.svn/entries",
     re.compile(r"^\s*\d+\s*$", re.MULTILINE),
     ".svn/entries"),
    ("/composer.lock",
     re.compile(r'"_readme"|"packages"\s*:'),
     "composer.lock"),
    ("/yarn.lock",
     re.compile(r"^# THIS IS AN AUTOGENERATED FILE\.|^[\w@\-/]+@.+:$",
                 re.MULTILINE),
     "yarn.lock"),
    ("/package-lock.json",
     re.compile(r'"lockfileVersion"\s*:\s*\d'),
     "package-lock.json"),
    ("/package.json.bak",
     re.compile(r'"name"\s*:\s*"|"dependencies"\s*:'),
     "package.json.bak"),
    ("/wp-config.php.bak",
     re.compile(r"DB_NAME|DB_PASSWORD"),
     "wp-config.php.bak"),
    ("/.htpasswd",
     re.compile(r"(?m)^[A-Za-z0-9_\-]+:\$"),
     ".htpasswd"),
    ("/server.key",
     re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
     "server.key"),
    ("/id_rsa",
     re.compile(r"-----BEGIN (?:RSA |OPENSSH )?PRIVATE KEY-----"),
     "id_rsa"),
    ("/private.key",
     re.compile(r"-----BEGIN (?:RSA |EC )?PRIVATE KEY-----"),
     "private.key"),
    ("/Dockerfile",
     re.compile(r"^\s*FROM\s+\S+", re.MULTILINE),
     "Dockerfile"),
    ("/docker-compose.yml",
     re.compile(r"(?m)^services\s*:\s*"),
     "docker-compose.yml"),
)


class InfoBackupFilesRootProbe(Probe):
    name = "info_backup_files_root"
    summary = ("Detects backup / config / source-control files exposed "
               "at the web root (signature-matched, not just 200).")
    safety_class = "read-only"

    def add_args(self, parser):
        parser.add_argument(
            "--max-paths", type=int, default=24,
            help="Cap on number of paths tested (default 24).")

    def run(self, args, client: SafeClient) -> Verdict:
        if not args.url:
            return Verdict(ok=False, error="--url is required")
        parsed = urlparse(args.url)
        origin = f"{parsed.scheme}://{parsed.netloc}"

        attempts: list[dict] = []
        confirmed: list[dict] = []
        cap = max(1, int(args.max_paths or 24))
        for (p, pat, label) in TARGETS[:cap]:
            url = urljoin(origin, p)
            r = client.request("GET", url)
            row: dict = {"path": p, "status": r.status, "size": r.size,
                         "label": label}
            if r.status == 200 and r.body:
                if pat.search(r.text or ""):
                    row["signature_match"] = True
                    row["snippet"] = (r.text or "")[:200]
                    confirmed.append(row)
                    attempts.append(row)
                    if len(confirmed) >= 3:
                        break
                    continue
            attempts.append(row)

        evidence = {"origin": origin, "attempts": attempts}
        if confirmed:
            top = confirmed[0]
            return Verdict(
                validated=True, confidence=0.95,
                summary=(
                    f"Confirmed: backup/config file exposed at "
                    f"{origin}{top['path']} ({top['label']}). The "
                    "response body matches the file format's signature "
                    f"-- snippet: {top.get('snippet','')[:160]!r}. "
                    f"{len(confirmed)} file(s) leak in total."),
                evidence={**evidence, "confirmed": confirmed},
                severity_uplift="critical",
                remediation=(
                    "Remove the file from the document root; if the "
                    "deploy pipeline keeps regenerating it, fix the "
                    "pipeline.\n"
                    "  - .env / config.json / config.yaml: store outside "
                    "the doc root, load via the framework's config "
                    "loader at boot. Rotate every secret the file "
                    "leaked -- assume it's already public.\n"
                    "  - .git/.svn: tighten the deploy script (rsync "
                    "with --exclude='.git', or `git archive` for "
                    "release tarballs). At the edge, add a 404 rule "
                    "for `^/\\.(git|svn)/`.\n"
                    "  - private keys: rotate immediately; investigate "
                    "whether the key has been used anywhere off-host.\n"
                    "  - SQL dumps: delete and audit who's accessed "
                    "them in the access logs."),
            )
        return Verdict(
            validated=False, confidence=0.85,
            summary=(f"Refuted: tested {len(attempts)} backup/config "
                     f"paths on {origin}; none returned content "
                     "matching the per-file signature."),
            evidence=evidence,
        )


if __name__ == "__main__":
    InfoBackupFilesRootProbe().main()
